title: Eli Regen # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  A former phyciscist turned Data scientist
  After completing my Master of Science degree in physics at Illinois Institute of Technology I have decided to pivot into Data Science.  
  I am excited to leverage the skills I employed in academia; namely problem-solving, research, mathematical modeling, and data visualization to produce comprehensive and illuminating reports on big data.  
  In my spare time I like to tinker with hardware, read obscure fiction (once and future king, Phantastes, Lilith), and pour over youtube videos of dogs playing with babies.

  <a href="https://www.linkedin.com/in/eli-regen-6a1413129/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
